version: '3'
services:
  web:
    build: .
    expose:
      - "3000"
    volumes:
      - data:/app/data
  nginx:
    image: nginx:alpine
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.template:/etc/nginx/nginx.template:ro
      - ./nginx-entrypoint.sh:/usr/local/bin/nginx-entrypoint.sh:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
    command: /usr/local/bin/nginx-entrypoint.sh
volumes:
  data:
